export enum STATUS_CODES {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
    UNSUPPORTED_MEDIA_TYPE = 415,
    INTERNAL_SEVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    INSUFFICIENT_STORAGE = 507
}

export enum ACCESS_MODIFIERS {
    PRIVATE = 'PRIVATE',
    PUBLIC = 'PUBLIC',
    READONLY = 'READONLY'
}

export enum ROLE_SCOPES {
    READ  = 'READ',
    DELETE = 'DELETE',
    WRITE = 'WRITE',
    UPDATE = 'UPDATE'
}
